### ISSUE TITLE
[FEAT]: Switching Between PAT and GitHub App Authentication Without Modifying Terraform Code

### ISSUE THREAD

**Issue by twokasa** [integrations/terraform-provider-github#1877]
### Describe the need

Hello,

I'm trying to differentiate between authentication methods: using PAT (Personal Access Token) in my local environment and the GitHub App in the CI environment. However, after adding the app_auth block for the CI setup, I receive an error in the local environment indicating that id, installation_id, and pem_file are not set. Is there a way to toggle between authentication methods without changing the Terraform code?

Thank you for your assistance.

(Note: This message was translated with the assistance of a machine translation tool.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hi! Unfortunately there is currently no way to do so. That would be an interesting feature to add!

**Comment by wheelerlaw** [comment]
You can do this by using the GitHub CLI (`gh`) to authenticate. To do this, leave the `provider "github"` block empty. Then, make sure you have your local credentials configured by doing `gh auth login`. In your CI you will need to generate an app installation token from the app's private key. The following is an example if you are using GitHub Actions:

```yaml
name: CI
on:
  push:
    branches: [main]
jobs:
  apply:
    name: TF Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate app token
        id: generate-app-token
        uses: tibdex/github-app-token@v1.9.0
        with:
          app_id: ${{ vars.YOUR_APP_ID }}
          private_key: ${{ secrets.YOUR_APP_PRIVATE_KEY }}
      - name: Terraform apply
        env:
          GITHUB_TOKEN: ${{ steps.generate-app-token.outputs.token }}
        run: terraform apply -auto-approve
```
