### ISSUE TITLE
[BUG]:  Unable to generate template repository after upgrade 

### ISSUE THREAD

**Issue by muawiakh** [integrations/terraform-provider-github#2021]
### Expected Behavior

We are generating some repositories from our `internal template(s)` and this worked fine until we upgraded `terraform-provider-github` i.e.

```
version = ">= 4.17.0" -> version = ">= 5.40"
```

For authentication we were using a Github App and generating a token using the following workflow:

```
      - name: "Generate App Authentication Token for Github"
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app_id: ${{ secrets.OUR_APP_ID }}
          private_key: ${{ secrets.OUR_PRIVATE_KEY }}
          owner: "orgname"
```

### Actual Behavior

After the upgrade, we are receiving a 404 from the Github API:

```
Error: POST https://api.github.com/repos/myorg/template-repo/generate: 404 Not Found []
```

In the [Github API documentation](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-using-a-template) , it is missing the `Works with GitHub Apps` sign as well and also needs a `UAT` based on the latest documentation: https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28

Based on the release notes, we are unable pinpoint, when the provider started failing using the App Token.  We would like to stay up-to-date with the provider version and figure out if this is an issue or if we should use a `user-to-server` token for template repository creations.

### Terraform Version

terraform_version: 1.6.3

### Affected Resource(s)

- github_repository

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.6.0"
  required_providers {
    github = {
      source  = "integrations/github"
      version = ">= 5.40"
    }
  }
}

resource "github_repository" "this" {
  name        = var.name
  description = var.description
  visibility  = var.visibility

  topics = var.topics

  has_issues    = var.has_issues
  has_projects  = var.has_projects
  has_wiki      = var.has_wiki
  has_downloads = var.has_downloads

  is_template = var.is_a_template

  dynamic "template" {
    for_each = var.template != null ? [var.template] : []

    content {
      owner      = template.value.owner
      repository = template.value.repository
    }
  }

  allow_auto_merge   = var.allow_auto_merge
  allow_merge_commit = var.allow_merge_commit
  allow_rebase_merge = var.allow_rebase_merge
  allow_squash_merge = var.allow_squash_merge

  delete_branch_on_merge = true

  auto_init           = true
  allow_update_branch = var.allow_update_branch
}
```

### Steps to Reproduce

terraform apply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
