### ISSUE TITLE
[BUG]: `403 Resource not accessible by integration []`

### ISSUE THREAD

**Issue by garysassano** [integrations/terraform-provider-github#2226]
### Expected Behavior

Be able to create a repository using `${{ secrets.GITHUB_TOKEN }}` instead of a PAT.

### Actual Behavior

Can only create a repo using `${{ secrets.MY_PAT}}`, since even a `GITHUB_TOKEN` with full write permissions doesn't have the rights to create a new repository when used with the [integrations/github](https://registry.terraform.io/providers/integrations/github/latest/docs) Terraform provider.

```sh
│ Error: POST https://api.github.com/user/repos: 403 Resource not accessible by integration []
│ 
│   with github_repository.SampleRepo,
      + allow_merge_commit          = false
      + allow_rebase_merge          = false
│   on main.tf line 14, in resource "github_repository" "SampleRepo":
│   14: resource "github_repository" "SampleRepo" {
│ 
```

```yaml
jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
    - uses: actions/checkout@v4
    
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![image](https://github.com/integrations/terraform-provider-github/assets/10464497/3bfe8b05-6da1-4a87-83dd-93bbb47ad603)

### Terraform Version

Terraform v1.8.0 on linux_amd64 + provider registry.terraform.io/integrations/github v6.2.1

### Affected Resource(s)

- `github_repository`
- `github_branch_protection`

### Terraform Configuration Files

```hcl
#### main.tf


terraform {
  required_providers {
    github = {
      version = "6.2.1"
      source  = "integrations/github"
    }
  }
}

provider "github" {}

resource "github_repository" "SampleRepo" {
  name                        = "todelete_sample"
  visibility                  = "private"
  allow_auto_merge            = false
  allow_merge_commit          = false
  allow_rebase_merge          = false
  allow_squash_merge          = true
  allow_update_branch         = true
  auto_init                   = true
  delete_branch_on_merge      = true
  has_discussions             = false
  has_downloads               = true
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "PR_TITLE"
}

resource "github_branch_protection" "MainBranchProtection" {
  repository_id                   = github_repository.SampleRepo.node_id
  pattern                         = "main"
  allows_deletions                = false
  allows_force_pushes             = false
  enforce_admins                  = true
  require_conversation_resolution = true
  required_pull_request_reviews {
    dismiss_stale_reviews           = true
    required_approving_review_count = 1
  }
  required_status_checks {
    strict = true
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
